### PR TITLE
Improve testing

### PR DESCRIPTION
**Pull request by andreww**
These changes:

* Enable tests when we change .ipynb files
* Run tests on windows and osx (as well as linux)
* Change notebooks so that these tests pass on windows
* Turn on coverage reporting for tests
* Turn on linting with flake8

### CODE REVIEW

**Comment by andreww** [comment]
Resolves #3

**Comment by andreww** [comment]
Currently fails on windows for jupyter notebooks (looks like a path issue for the data in the notebooks)

**Comment by andreww** [comment]
Partial fix for #7 too - turns on linting. The rest needs some text on developing for the documentation I think

**Review by TomSHudson — APPROVED** [review]
Changes all look fine. I'll check for any further notebook path issues and update docs requirements.

**Pull request merged**
